---
# tasks file for lb-tier-teardown
- name: Remove load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: absent

- name: configure haproxy
  file:
    path: /etc/haproxy/haproxy.cfg
    state: absent
