---
# tasks file for osp-instance-clean-up

- name: Fetch Instance Info
  openstack.cloud.server_info:
    cloud: "{{ guid }}-project"
    server:  "{{ inventory_hostname }}"
    filters:
      vm_state: active
  delegate_to: control
  register: result

- name: print debug
  debug:
    var: result.openstack_servers[0].name

- name: Delete instances
  os_server:
    cloud: "{{ guid }}-project"
    name: "{{ result.openstack_servers[0].name }}"
    state: absent
  delegate_to: control
  when: result != ""
