- name: Fetch Instance Info
  openstack.cloud.server_info:
    cloud: "{{ guid }}-project"
    server:  "{{ instance.name }}"
  register: result

- name: print data
  debug:
    msg: "{[ result.openstack_servers }}"


- name: Wait for instance to be available
  wait_for:
    host: "{{ result.openstack_servers[0].accessIPv4 }}"
    port: 22
    search_regex: OpenSSH
    timeout: 120
  delegate_to: "{{ inventory_hostname }}"
