---
# tasks file for osp-instance-provision

- include_tasks: get-dns.yml

- include_tasks: provision-server.yml

- include_tasks: check_connectivity.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance
