---
- name: Create Instance
  openstack.cloud.server:
    cloud: "{{ guid }}-project"
    name: "{{ instance.name }}"
    image: "{{ instance.image }}"
    key_name: "{{ instance.keypair }}"
    flavor: "{{ instance.flavor }}"
    security_groups: "{{ instance.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: "{{ instance.internal_network }}"
#    meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}}, group={{instance.metadata.group}}"
    meta: "{{ instance.metadata }}"
    userdata: |
       #!/bin/bash
       echo 'PEERDNS=no' |sudo  tee -a /etc/sysconfig/network-scripts/ifcfg-eth0 >/dev/null
       echo 'DNS1={{hostvars.control.ansible_default_ipv4.address}}' |sudo  tee -a /etc/sysconfig/network-scripts/ifcfg-eth0 >/dev/null
       sudo systemctl restart NetworkManager
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance
 
