---
- name: Create Instance
  openstack.cloud.server:
    cloud: "{{ guid }}-project"
    name: "{{ instance.name }}"
    image: "{{ instance.image }}"
    key_name: "{{ instance.keypair }}"
    flavor: "{{ instance.flavor }}"
    security_groups: "{{ instance.security_group }}"
    delete_fip: yes
    wait: yes
    nics:
      - net-name: "{{ instance.internal_network }}"
    meta: "{{ instance.metadata }}"
    userdata: |
      #!/bin/bash
      echo 'PEERDNS=no' |sudo  tee -a /etc/sysconfig/network-scripts/ifcfg-eth0 >/dev/null
      echo 'DNS1={{hostvars.control.ansible_default_ipv4.address}}' |sudo  tee -a /etc/sysconfig/network-scripts/ifcfg-eth0 >/dev/null
      sudo systemctl restart NetworkManager
#  loop: "{{ instances }}"
#  loop_control:
#    loop_var: instance

- name: Fetch Instance Info
  openstack.cloud.server_info:
    cloud: "{{ guid }}-project"
    server:  "{{ instance.name }}"
  register: result

 
- name: Wait for instance to be available
  wait_for:
    host: "{{ result.openstack_servers[0].ansible_host }}"
    port: 22
    search_regex: OpenSSH
    timeout: 300
  delegate_to: "{{ inventory_hostname }}"
