---
# tasks file for osp-instance-check-connectivity

- name: Refresh inventory to ensure new instances exist in inventory
  meta: refresh_inventory

- name: Wait for system to become reachable
  wait_for_connection:
    delay: 30
    timeout: 120

