---
# tasks file for osp-instance-check-connectivity

#- name: Refresh inventory to ensure new instances exist in inventory
#  meta: refresh_inventory

- name: Wait for system to become reachable
  wait_for_connection:
    delay: 30
    timeout: 180

#- name: Check connevtivity to provisoned servers
#  ping:

- name: Pause play until a URL is reachable from this host
  uri:
    url: "http://satellite.example.com"
#    follow_redirects: none
    validate_certs: no
    method: GET
  register: _result
  until: _result.status == 200
  retries: 720 
  delay: 5 
