---
- name: Gather DNS Server IP address
  hosts: control.example.com

  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - 'network'
#      delegate_facts: true
#      delegate_to: localhost
#      connection: local

    - name: print value
      debug:
         msg: "DNS Server to use: {{ansible_eth0.ipv4.address}}"

- name: Create OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    guid: "{{ lookup('ENV','GUID') }}"
  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml

    - name: Create Instance
      openstack.cloud.server:
        cloud: "{{ guid }}-project"
        name: "{{ instance.name }}"
        image: "{{ instance.image }}"
        key_name: "{{ instance.keypair }}"
        flavor: "{{ instance.flavor }}"
        security_groups: "{{ instance.security_group }}"
        delete_fip: yes
        wait: no
        nics:
          - net-name: "{{ instance.internal_network }}"
        meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}}"
        userdata: |
           #!/bin/bash
           echo 'PEERDNS=no' |sudo  tee -a /etc/sysconfig/network-scripts/ifcfg-eth0 >/dev/null
           echo 'DNS1={{hostvars.localhost.ansible_default_ipv4.address}}' |sudo  tee -a /etc/sysconfig/network-scripts/ifcfg-eth0 >/dev/null
           sudo systemctl restart NetworkManager
      loop: "{{ instances }}"
      loop_control:
        loop_var: instance
