---
# tasks file for roles/osp-instance-delete
- name: Delete OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    guid: "{{ lookup('ENV','GUID') }}"
  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml

    - name: calling block 
      include_tasks: osp-instance-delete-loop.yml
      loop: ['front*','app*']
