---
- name: Gather DNS Server IP address
  hosts: controls

  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - 'network'
      delegate_facts: true
      delegate_to: localhost
      connection: local

    - name: print value
      debug:
         var: hostvars["control.example.com"].ansible_default_ipv4.address
