---
guid: "{{ lookup('ENV','GUID') }}"

instances:
  - name: app1
    keypair: 2b0e-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 2b0e-HostSG
    internal_network: 2b0e-dev-network
    metadata:
      AnsibleGroup: app_servers 
      deployment_name: ansible-labs

  - name: app2
    keypair: 2b0e-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 2b0e-HostSG
    internal_network: 2b0e-dev-network
    metadata:
      AnsibleGroup: app_servers
      deployment_name: ansible-labs

  - name: appdb1
    keypair: 2b0e-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 2b0e-HostSG
    internal_network: 2b0e-dev-network
    metadata:
      AnsibleGroup: app_servers
      deployment_name: ansible-labs

  - name: frontend1
    keypair: 2b0e-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 2b0e-HostSG
    internal_network: 2b0e-dev-network
    metadata:
      AnsibleGroup: app_servers
      deployment_name: ansible-labs
